// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backendTask.DBContext;

#nullable disable

namespace backendTask.Migrations.AddressDB
{
    [DbContext(typeof(AddressDBContext))]
    [Migration("20231107222356_Addresses")]
    partial class Addresses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backendTask.DBContext.Models.as_addr_obj", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("changeid")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("enddate")
                        .HasColumnType("date");

                    b.Property<int?>("isactual")
                        .HasColumnType("integer");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("nextid")
                        .HasColumnType("bigint");

                    b.Property<Guid>("objectguid")
                        .HasColumnType("uuid");

                    b.Property<long>("objectid")
                        .HasColumnType("bigint");

                    b.Property<int?>("opertypeid")
                        .HasColumnType("integer");

                    b.Property<long?>("previd")
                        .HasColumnType("bigint");

                    b.Property<int?>("sactive")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("startdate")
                        .HasColumnType("date");

                    b.Property<string>("typename")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("updatedate")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("as_addr_obj");
                });

            modelBuilder.Entity("backendTask.DBContext.Models.as_adm_hierachy", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("areacode")
                        .HasColumnType("text");

                    b.Property<long?>("changeid")
                        .HasColumnType("bigint");

                    b.Property<string>("citycode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("enddate")
                        .HasColumnType("date");

                    b.Property<int?>("isactive")
                        .HasColumnType("integer");

                    b.Property<long?>("nextid")
                        .HasColumnType("bigint");

                    b.Property<long?>("objectid")
                        .HasColumnType("bigint");

                    b.Property<long?>("parentobjid")
                        .HasColumnType("bigint");

                    b.Property<string>("path")
                        .HasColumnType("text");

                    b.Property<string>("placecode")
                        .HasColumnType("text");

                    b.Property<string>("plancode")
                        .HasColumnType("text");

                    b.Property<long?>("previd")
                        .HasColumnType("bigint");

                    b.Property<string>("regioncode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("startdate")
                        .HasColumnType("date");

                    b.Property<string>("streetcode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("updatedate")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("as_adm_hierachy");
                });

            modelBuilder.Entity("backendTask.DBContext.Models.as_houses", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("addnum1")
                        .HasColumnType("text");

                    b.Property<string>("addnum2")
                        .HasColumnType("text");

                    b.Property<int?>("addtype1")
                        .HasColumnType("integer");

                    b.Property<int?>("addtype2")
                        .HasColumnType("integer");

                    b.Property<long?>("changeid")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("enddate")
                        .HasColumnType("date");

                    b.Property<string>("housenum")
                        .HasColumnType("text");

                    b.Property<int?>("housetype")
                        .HasColumnType("integer");

                    b.Property<int?>("isactive")
                        .HasColumnType("integer");

                    b.Property<int?>("isactual")
                        .HasColumnType("integer");

                    b.Property<long?>("nextid")
                        .HasColumnType("bigint");

                    b.Property<Guid>("objectguid")
                        .HasColumnType("uuid");

                    b.Property<long>("objectid")
                        .HasColumnType("bigint");

                    b.Property<int?>("opertypeid")
                        .HasColumnType("integer");

                    b.Property<long?>("orevid")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("startdate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("updatedate")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("as_houses");
                });
#pragma warning restore 612, 618
        }
    }
}
