// <auto-generated />
using System;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backendTask.DBContext;

#nullable disable

namespace backendTask.Migrations.AddressDB
{
    [DbContext(typeof(AddressDBContext))]
    [Migration("20231107152632_Addresses")]
    partial class Addresses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backendTask.DBContext.Models.as_addr_obj", b =>
                {
                    b.Property<BigInteger>("id")
                        .HasColumnType("numeric");

                    b.Property<BigInteger>("changeid")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("enddate")
                        .HasColumnType("date");

                    b.Property<int>("isactive")
                        .HasColumnType("integer");

                    b.Property<int>("isactual")
                        .HasColumnType("integer");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<BigInteger>("nextid")
                        .HasColumnType("numeric");

                    b.Property<Guid>("objectguid")
                        .HasColumnType("uuid");

                    b.Property<BigInteger>("objectid")
                        .HasColumnType("numeric");

                    b.Property<int>("opertypeid")
                        .HasColumnType("integer");

                    b.Property<BigInteger>("previd")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("startdate")
                        .HasColumnType("date");

                    b.Property<string>("typename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("updatedate")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("as_addr_obj");
                });

            modelBuilder.Entity("backendTask.DBContext.Models.as_adm_hierachy", b =>
                {
                    b.Property<BigInteger>("id")
                        .HasColumnType("numeric");

                    b.Property<string>("areacode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<BigInteger>("changeid")
                        .HasColumnType("numeric");

                    b.Property<string>("citycode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("enddate")
                        .HasColumnType("date");

                    b.Property<int>("isactive")
                        .HasColumnType("integer");

                    b.Property<BigInteger>("objectid")
                        .HasColumnType("numeric");

                    b.Property<BigInteger>("parentobjid")
                        .HasColumnType("numeric");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("placecode")
                        .HasColumnType("integer");

                    b.Property<BigInteger>("plancode")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("previd")
                        .HasColumnType("date");

                    b.Property<string>("regioncode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("startdate")
                        .HasColumnType("date");

                    b.Property<BigInteger>("streetcode")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("updatedate")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("as_adm_hierachy");
                });

            modelBuilder.Entity("backendTask.DBContext.Models.as_houses", b =>
                {
                    b.Property<BigInteger>("id")
                        .HasColumnType("numeric");

                    b.Property<string>("addnum1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("addnum2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("addtype1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("addtype2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<BigInteger>("changeid")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("enddate")
                        .HasColumnType("date");

                    b.Property<string>("housenum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("housetype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("isactive")
                        .HasColumnType("integer");

                    b.Property<int>("isactual")
                        .HasColumnType("integer");

                    b.Property<BigInteger>("nextid")
                        .HasColumnType("numeric");

                    b.Property<Guid>("objectguid")
                        .HasColumnType("uuid");

                    b.Property<BigInteger>("objectid")
                        .HasColumnType("numeric");

                    b.Property<int>("opertypeid")
                        .HasColumnType("integer");

                    b.Property<BigInteger>("previd")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("startdate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("updatedate")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("as_houses");
                });
#pragma warning restore 612, 618
        }
    }
}
